services:
  nsxlibrarymanager:
    container_name: nsxlibrarymanager
    # Docker Hub에서 이미지 사용 (권장)
    image: [YOUR_DOCKERHUB_USERNAME]/nsxlibrarymanager:latest
    # 또는 로컬에서 빌드하려면 아래 주석을 해제하고 위 image 라인을 주석처리
    # build:
    #   context: .
    volumes:
      - /mnt/nfs/library:/app/library
      - /srv/nsxlibrarymanager/icon:/app/wwwroot/images/icon
      - /srv/nsxlibrarymanager/config:/app/config
      - /srv/nsxlibrarymanager/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '8080:8080'
    environment:
      - PUID=1000
      - PGID=1000
    restart: always